### ISSUE TITLE
The 'VFPOLEDB.1' provider is not registered on the local machine

### ISSUE THREAD

**Issue by ChayoteJarocho** [ChayoteJarocho/FoxProDatabaseExtractor#5]
When executing:
```
dotnet run -- FoxProDataBaseExtractor.csproj mydb.dbc output/
```

The following error shows up:

```
Unhandled exception. System.InvalidOperationException: The 'VFPOLEDB.1' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at FoxProDatabaseExtractor.FoxProDatabaseConnector..ctor(String databasePath) in E:\repos\FoxProDatabaseExtractor\src\FoxProDatabaseConnector.cs:line 41
   at FoxProDatabaseExtractor.Program.Main(String[] args) in E:\repos\FoxProDatabaseExtractor\src\Program.cs:line 87
```

**Comment by ChayoteJarocho** [comment]
The root cause is that VFP9 is x86 only, and the project is currently being built for `AnyCPU`. The fix is to force building for `x86`, and the tool works now.

Source: https://stackoverflow.com/questions/15684575/getting-the-error-the-vfpoledb-1-provider-is-not-registered-on-the-local-mach
